/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JoshA;


import org.springframework.boot.SpringApplication; 
import org.springframework.boot.autoconfigure.SpringBootApplication; 
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.boot.builder.SpringApplicationBuilder; 
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.context.annotation.Bean;

import org.springframework.cloud.config.server.EnableConfigServer;

@SpringBootApplication
@EnableConfigServer
public class Main extends SpringBootServletInitializer{
    
    public static void main(String[] args){
        
        SpringApplication.run(Main.class, args); 
    }
    
    @Override  protected SpringApplicationBuilder configure(SpringApplicationBuilder application){
        
        return application.sources(Main.class);
    }
}


//Assuming that your server port is 8888 Enter this URL to see the properties file managed by this Spring Cloud Configuration Server

//In order to see config-client-dev.properties managed by this Spring Cloud Configuration Server
//http://localhost:8888/config-client-dev/default/master

//In order to see JoshClient-prod.properties managed by this Spring Cloud Configuration Server
//http://localhost:8888/JoshClient-prod/default/master

//In order to see JoshClient-dev.properties managed by this Spring Cloud Configuration Server
//http://localhost:8888/JoshClient-dev/default/master


