/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package JoshA;


import org.springframework.boot.SpringApplication; 
import org.springframework.boot.autoconfigure.SpringBootApplication; 
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.boot.builder.SpringApplicationBuilder; 
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
import org.springframework.context.annotation.Bean;
import org.springframework.beans.factory.annotation.Value;

import org.springframework.cloud.context.config.annotation.RefreshScope;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.core.env.Environment;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@SpringBootApplication
@RefreshScope
@RestController
public class Main extends SpringBootServletInitializer{
    
    @Value("${config-client-dev.welcome.message}")  
    public String str1;
    
    @Value("${JoshClient-dev.welcome.message}") 
    private String str2;
    
    @Value("${JoshClient-prod.welcome.message}") 
    private String str3;
    
    public static void main(String[] args){
        
        SpringApplication.run(Main.class, args); 
    }
    
    @RequestMapping(path="/welcomeText")
    public String welcomeText(){
        
        return str1+" AND "+str2+" AND "+str3;
    }
    
    @Override  protected SpringApplicationBuilder configure(SpringApplicationBuilder application){
        
        return application.sources(Main.class);
    }
}


//Make sure that Spring-CloudConfigServer-Build project which is our Spring Cloud Configuration Server that we will load this app configuration from is already running

//Then enter this GET url to see our welcomeText message
//http://localhost:8080/welcomeText

//Enter this POST request to refresh app configurations
//curl -X POST localhost:8080/actuator/refresh







